In [ ]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")

In [ ]:
loan_data  = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/Loan_Data/loan_train.csv" )
test_data= pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/Loan_Data/loan_test.csv')

loan_data.head()

Unnamed: 0   Loan_ID  Gender  ... Credit_History Property_Area Loan_Status
0           0  LP002305  Female  ...            1.0     Semiurban           1
1           1  LP001715    Male  ...            1.0         Rural           1
2           2  LP002086  Female  ...            1.0         Urban           0
3           3  LP001136    Male  ...            1.0         Urban           1
4           4  LP002529    Male  ...            1.0     Semiurban           1

[5 rows x 14 columns]

In [ ]:
test_data.head()

Loan_ID Gender Married  ... Loan_Amount_Term Credit_History Property_Area
0  LP001116   Male      No  ...            360.0            1.0     Semiurban
1  LP001488   Male     Yes  ...            360.0            1.0     Semiurban
2  LP002138   Male     Yes  ...            360.0            1.0         Rural
3  LP002284   Male      No  ...            360.0            1.0         Rural
4  LP002328   Male     Yes  ...            360.0            0.0         Rural

[5 rows x 12 columns]

In [ ]:
loan_data.describe().transpose()

count         mean          std  ...     50%     75%      max
Unnamed: 0         491.0   245.000000   141.883755  ...   245.0   367.5    490.0
ApplicantIncome    491.0  5401.189409  6419.427177  ...  3865.0  5705.5  81000.0
CoapplicantIncome  491.0  1589.730998  2919.320624  ...  1229.0  2251.5  41667.0
LoanAmount         475.0   145.014737    86.310534  ...   126.0   162.0    700.0
Loan_Amount_Term   478.0   341.297071    66.964051  ...   360.0   360.0    480.0
Credit_History     448.0     0.848214     0.359214  ...     1.0     1.0      1.0
Loan_Status        491.0     0.698574     0.459345  ...     1.0     1.0      1.0

[7 rows x 8 columns]

In [ ]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 491 entries, 0 to 490
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         491 non-null    int64  
 1   Loan_ID            491 non-null    object 
 2   Gender             481 non-null    object 
 3   Married            490 non-null    object 
 4   Dependents         482 non-null    object 
 5   Education          491 non-null    object 
 6   Self_Employed      462 non-null    object 
 7   ApplicantIncome    491 non-null    int64  
 8   CoapplicantIncome  491 non-null    float64
 9   LoanAmount         475 non-null    float64
 10  Loan_Amount_Term   478 non-null    float64
 11  Credit_History     448 non-null    float64
 12  Property_Area      491 non-null    object 
 13  Loan_Status        491 non-null    int64  
dtypes: float64(4), int64(3), object(7)
memory usage: 53.8+ KB


In [ ]:
loan_data.drop(columns=['Unnamed: 0', 'Loan_ID'], axis=1, inplace= True)
test_data.drop('Loan_ID', axis=1, inplace= True)
loan_data.isnull().sum()

Gender               10
Married               1
Dependents            9
Education             0
Self_Employed        29
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           16
Loan_Amount_Term     13
Credit_History       43
Property_Area         0
Loan_Status           0
dtype: int64

#Filling up missing values

In [ ]:
loan_data['Gender'].value_counts()

Male      393
Female     88
Name: Gender, dtype: int64

In [ ]:
loan_data['Gender']= loan_data['Gender'].apply(lambda x: 1 if x == 'Male' else 0)
test_data['Gender']= test_data['Gender'].apply(lambda x: 1 if x == 'Male' else 0)
loan_data['Gender'].isnull().sum()

0

In [ ]:
loan_data['Married']= loan_data.Married.apply(lambda x: 1 if x == "Yes" else 0)
test_data['Married']= test_data.Married.apply(lambda x: 1 if x == "Yes" else 0)

loan_data['Married'].isnull().sum()

0

In [ ]:
loan_data['Dependents']= loan_data.Dependents.astype('category')
test_data['Dependents']= test_data.Dependents.astype('category')

loan_data['Dependents'].fillna("0", inplace = True)

In [ ]:
loan_data['Dependents'].value_counts()

0     285
1      85
2      78
3+     43
Name: Dependents, dtype: int64

In [ ]:
loan_data['Self_Employed'].value_counts()

No     398
Yes     64
Name: Self_Employed, dtype: int64

In [ ]:
loan_data['Self_Employed'] = loan_data.Self_Employed.apply(lambda x: 1 if x == 'Yes' else 0)

test_data['Self_Employed'] = test_data.Self_Employed.apply(lambda x: 1 if x == 'Yes' else 0)

In [ ]:
loan_data['LoanAmount'].fillna(loan_data['LoanAmount'].median(), inplace= True)
loan_data['Loan_Amount_Term'].fillna(loan_data['Loan_Amount_Term'].mean(), inplace= True)

test_data['LoanAmount'].fillna(test_data['LoanAmount'].median(), inplace= True)
test_data['Loan_Amount_Term'].fillna(test_data['Loan_Amount_Term'].mean(), inplace= True)

In [ ]:
loan_data['Credit_History'].value_counts()

1.0    380
0.0     68
Name: Credit_History, dtype: int64

In [ ]:
loan_data['Credit_History'].fillna(1, inplace= True)

test_data['Credit_History'].fillna(1, inplace= True)

In [ ]:
loan_data.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

# Preparing data for One Hot Encoding

In [ ]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 491 entries, 0 to 490
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype   
---  ------             --------------  -----   
 0   Gender             491 non-null    int64   
 1   Married            491 non-null    int64   
 2   Dependents         491 non-null    category
 3   Education          491 non-null    object  
 4   Self_Employed      491 non-null    int64   
 5   ApplicantIncome    491 non-null    int64   
 6   CoapplicantIncome  491 non-null    float64 
 7   LoanAmount         491 non-null    float64 
 8   Loan_Amount_Term   491 non-null    float64 
 9   Credit_History     491 non-null    float64 
 10  Property_Area      491 non-null    object  
 11  Loan_Status        491 non-null    int64   
dtypes: category(1), float64(4), int64(5), object(2)
memory usage: 43.0+ KB


In [ ]:
loan_data['Education']= loan_data.Education.apply(lambda x: 0 if x== 'Not Graduate' else 1)
loan_data['Property_Area']= loan_data['Property_Area'].astype('category')

test_data['Education']= test_data.Education.apply(lambda x: 0 if x== 'Not Graduate' else 1)
test_data['Property_Area']= test_data['Property_Area'].astype('category')

In [ ]:
loan_data = pd.get_dummies(loan_data)

test_data= pd.get_dummies(test_data)
loan_data.head()

Gender  Married  ...  Property_Area_Semiurban  Property_Area_Urban
0       0        0  ...                        1                    0
1       1        1  ...                        0                    0
2       0        1  ...                        0                    1
3       1        1  ...                        0                    1
4       1        1  ...                        1                    0

[5 rows x 17 columns]

In [ ]:
X= loan_data.drop('Loan_Status', axis=1)
y= loan_data['Loan_Status']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test= train_test_split(X,y, test_size= 0.2, random_state= 42)

In [ ]:
from sklearn.linear_model import LogisticRegression

model_LR= LogisticRegression()
model_LR.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
from sklearn.model_selection import cross_val_score

cross_val_score(model_LR, X_train,y_train, cv= 5)

array([0.81012658, 0.78481013, 0.78205128, 0.82051282, 0.76923077])

In [ ]:
from sklearn.feature_selection import RFE

LR= LogisticRegression()
selector= RFE(LR, step=1)
selector.fit(X_train, y_train)

print("Number of features selected for the model to train on: {}".format(selector.support_.sum()))
print("\n")
print("The ranking of all the features are as follows: ")
selector.ranking_

Number of features selected for the model to train on: 8


The ranking of all the features are as follows: 


array([2, 1, 1, 3, 9, 8, 6, 7, 1, 5, 1, 1, 4, 1, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score, f1_score

y_pred_RFE= selector.predict(X_test)
print(accuracy_score(y_pred_RFE, y_test))
print(f1_score(y_pred_RFE, y_test))

0.8282828282828283
0.8843537414965986


In [ ]:
prediction= selector.predict(test_data)
prediction_df= pd.DataFrame(prediction, columns=['prediction'])
prediction_df.to_csv('prediction.csv', index= False)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

DTC= DecisionTreeClassifier(random_state=1)
params= {
    'max_leaf_nodes': [2,5,7,10, 15, 20], 
    'min_samples_split': [2,3,4, 6, 8, 10], 
    'min_samples_leaf': [1,3,5,7],
    'max_depth': [2,3,4,5,6]
}

GS= GridSearchCV(DTC, params, cv=3, n_jobs=-1, verbose=2)
GS.fit(X_train,y_train)
GS.best_params_

Fitting 3 folds for each of 720 candidates, totalling 2160 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done 668 tasks      | elapsed:    2.6s
[Parallel(n_jobs=-1)]: Done 2160 out of 2160 | elapsed:    8.0s finished


{'max_depth': 2,
 'max_leaf_nodes': 2,
 'min_samples_leaf': 1,
 'min_samples_split': 2}

In [ ]:
cross_val_score(GS, X_train, y_train, cv=5)

Fitting 3 folds for each of 720 candidates, totalling 2160 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done 668 tasks      | elapsed:    2.4s
[Parallel(n_jobs=-1)]: Done 2160 out of 2160 | elapsed:    7.6s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.


Fitting 3 folds for each of 720 candidates, totalling 2160 fits


[Parallel(n_jobs=-1)]: Done 668 tasks      | elapsed:    2.4s
[Parallel(n_jobs=-1)]: Done 2160 out of 2160 | elapsed:    7.6s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.


Fitting 3 folds for each of 720 candidates, totalling 2160 fits


[Parallel(n_jobs=-1)]: Done 668 tasks      | elapsed:    2.4s
[Parallel(n_jobs=-1)]: Done 2160 out of 2160 | elapsed:    7.8s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.


Fitting 3 folds for each of 720 candidates, totalling 2160 fits


[Parallel(n_jobs=-1)]: Done 668 tasks      | elapsed:    2.5s
[Parallel(n_jobs=-1)]: Done 2160 out of 2160 | elapsed:    7.8s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.


Fitting 3 folds for each of 720 candidates, totalling 2160 fits


[Parallel(n_jobs=-1)]: Done 668 tasks      | elapsed:    2.5s
[Parallel(n_jobs=-1)]: Done 2160 out of 2160 | elapsed:    7.7s finished


array([0.82278481, 0.79746835, 0.78205128, 0.83333333, 0.80769231])

In [ ]:
y_pred_DT= GS.predict(X_test)
print(accuracy_score(y_pred_DT, y_test))
f1_score(y_pred_DT, y_test)

0.8282828282828283


0.8843537414965986

In [ ]:
prediction2= GS.predict(test_data)
prediction_df2= pd.DataFrame(prediction2, columns=['prediction'])
prediction_df2.to_csv('prediction2.csv', index= False)